name = "mendix_doom"
version = "1.0.1"
target = "javascript"

[javascript]
typescript_declarations = false
runtime = "node"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glendix = ">= 3.0.0 and < 4.0.0"
redraw = ">= 19.2.2 and < 20.0.0"
redraw_dom = ">= 19.2.2 and < 20.0.0"
